### PR TITLE
Adding new resource xSmaCredential

### PR DESCRIPTION
**Pull request by dcrreynolds**
This change is [Reviewable](https://reviewable.io/reviews/powershell/xscsma/9)

### CODE REVIEW

**Comment by zjalali** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_[DSCResources/MSFT_xSmaCredential/MSFT_xSmaCredential.psm1, line 26 [r1]](https://reviewable.io:443/reviews/powershell/xscsma/9#-KON_xdbqL24pxE9PSbg:-KON_xdcL7lUnqvKdyVg:1832373380) ([raw file](https://github.com/powershell/xscsma/blob/d253e05cec881eb70059e0b193a521db8b7f3ab4/DSCResources/MSFT_xSmaCredential/MSFT_xSmaCredential.psm1#L26)):_

> ``` PowerShell
>     )
> 
>     $Set = $true
> ```

You are mixing **Get-TargetResource** and **Test-TargetResource** functions with this approach. I can see some value in refactoring the code but if that's the case, I propose a helper function. I was initially confused as what _$set_ was supposed to do.

---

_[Tests/Unit/MSFT_xSmaCredential.Test.ps1, line 48 [r1]](https://reviewable.io:443/reviews/powershell/xscsma/9#-KONcaXnLny4zm7VPnNE:-KONcaXnLny4zm7VPnNF:-2033516334) ([raw file](https://github.com/powershell/xscsma/blob/d253e05cec881eb70059e0b193a521db8b7f3ab4/Tests/Unit/MSFT_xSmaCredential.Test.ps1#L48)):_

> ```
>     It 'Get method returns set equal to false' {
>         $result = Get-TargetResource @testParameters
> ```
> 
> <details><summary>
> 
> <i alt="summary">Quoted 4 lines of code…</i></summary>
> 
> 
>             $result.name | Should Be $testParameters.Name
>             $result.WebServiceEndpoint | Should Be $testParameters.WebServiceEndpoint
>             $result.Set | Should Be 'False'
>         }
> </details>

Right now, if the name is incorrect, we would not even test _WebServiceEndpoint_ and _Set_ values. To make the test count deterministic, you can put the **Get-TargetResource** call in the **BeforeAll** section of a **Context** block, and have three different **It** statements each testing one of the values.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xscsma/9)_

**Comment by zjalali** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xscsma/9)_

**Comment by dcrreynolds** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_[DSCResources/MSFT_xSmaCredential/MSFT_xSmaCredential.psm1, line 26 [r1]](https://reviewable.io:443/reviews/powershell/xscsma/9#-KON_xdbqL24pxE9PSbg:-KOXH9SQFZmGnf5iWdbd:b-hfowxt) ([raw file](https://github.com/powershell/xscsma/blob/d253e05cec881eb70059e0b193a521db8b7f3ab4/DSCResources/MSFT_xSmaCredential/MSFT_xSmaCredential.psm1#L26)):_
<details><summary>

<i>Previously, zjalali (Zia Jalali) wrote…</i></summary>



> You are mixing **Get-TargetResource** and **Test-TargetResource** functions with this approach. I can see some value in refactoring the code but if that's the case, I propose a helper function. I was initially confused as what _$set_ was supposed to do.
> </details>
> Fixed this by moving the Get logic to the test function. Removed $Set and added $UserName to support the Test logic and provided clearer information on Get-DscConfiguration.

---

_[Tests/Unit/MSFT_xSmaCredential.Test.ps1, line 48 [r1]](https://reviewable.io:443/reviews/powershell/xscsma/9#-KONcaXnLny4zm7VPnNE:-KOXIIS5OoNErOLvo3On:b-uxs7f6) ([raw file](https://github.com/powershell/xscsma/blob/d253e05cec881eb70059e0b193a521db8b7f3ab4/Tests/Unit/MSFT_xSmaCredential.Test.ps1#L48)):_
<details><summary>

<i>Previously, zjalali (Zia Jalali) wrote…</i></summary>



> > ```
> >     It 'Get method returns set equal to false' {
> >         $result = Get-TargetResource @testParameters
> > 
> >         $result.name | Should Be $testParameters.Name
> >         $result.WebServiceEndpoint | Should Be $testParameters.WebServiceEndpoint
> >         $result.Set | Should Be 'False'
> >     }
> > ```
> 
> Right now, if the name is incorrect, we would not even test _WebServiceEndpoint_ and _Set_ values. To make the test count deterministic, you can put the **Get-TargetResource** call in the **BeforeAll** section of a **Context** block, and have three different **It** statements each testing one of the values.
> </details>
> Running Get-TargetResource before all test wouldn't fit the scenario based pattern of the unit test template. Since the test is to test Get-TargetResource's results, I think it should test the output of the entire of the object.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xscsma/9)_

**Comment by zjalali** [comment]
:lgtm:

---

Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xscsma/9#-:-KPV-ZAkOyVd2QrN7KBd:bnfp4nl)_

**Comment by zjalali** [comment]
Thanks David.

---

Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xscsma/9#-:-KONh1WDD82trE2QfQyK:b71fo24)_

**Comment by zjalali** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xscsma/9)_

**Comment by kwirkykat** [comment]
@dcrreynolds PSSA issues that are failing your tests have been fixed now in the dev branch. Can you please rebase/merge to pull in the changes from dev so that your tests will pass?

**Comment by dcrreynolds** [comment]
Their you go @kwirkykat, updated the issue in my test too.

**Comment by kwirkykat** [comment]
@dcrreynolds It looks like the new xSmaCredential tests you wrote aren't getting run in AppVeyor because the file name is missing an 's' in Tests.

Can you please rename the file to MSFT_xSmaCredential.Test**s**.ps1?

**Comment by dcrreynolds** [comment]
Took care of all of the test. It seems I'm consistent about leaving the 's' off...

**Comment by eshaparmar** [comment]
Reviewed 1 of 6 files at r1, 2 of 4 files at r2, 1 of 3 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xscsma/9)_

**Comment by eshaparmar** [comment]
Reviewed 1 of 4 files at r2, 2 of 6 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xscsma/9)_

**Comment by eshaparmar** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xscsma/9#-:-KS3aocGp9q_kdRJgx6W:bnfp4nl)_

**Pull request merged**
