### PR TITLE
Updated RunbookWorkerServerSetup and WebServiceServerSetup to use correct exe for version checking

### PR DESCRIPTION
**Pull request by dcrreynolds**
This is in response to issues #16 and #15

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xscsma/17)

### CODE REVIEW

**Comment by dcrreynolds** [comment]
Can I get a peer review for this please.

**Comment by TheBlackMini** [comment]
Any chance this will be merged soon?

**Comment by johlju** [comment]
@dcrreynolds Sorry that nobody review this PR before this. If I review this can you work on it?

**Comment by dcrreynolds** [comment]
I had completely forgotten about this! Please do. I'd love to get it checked in.

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xscsma/17#-:-LCmyvBH6s5Gxbeuik4E:bnfp4nl)*

**Comment by johlju** [comment]
Merging this as without tests as it is an obvious bug. Don't normally do that but make an exception this time. :)

**Pull request merged**
