### PR TITLE
Added new example to show removing the sample SMA runbooks with DSC

### PR DESCRIPTION
**Pull request by dcrreynolds**
This change is [Reviewable](https://reviewable.io/reviews/powershell/xscsma/5)

### CODE REVIEW

**Comment by FayzaSultan** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 122 [r1]](https://reviewable.io:443/reviews/powershell/xscsma/5#-KG-NQIHptP26gFfJnkZ:-KG-NQIHptP26gFfJnk_:451913107) ([raw file](https://github.com/powershell/xscsma/blob/62324f2a71a9cf1874415eac6239f2400bc4754e/README.md#L122)):_
Can you add a description of new example here along with file name. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xscsma/5)_

**Comment by dcrreynolds** [comment]
Updated. Thanks!

**Comment by TravisEz13** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xscsma/5)_

**Comment by dcrreynolds** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 122 [r1]](https://reviewable.io:443/reviews/powershell/xscsma/5#-KG-NQIHptP26gFfJnkZ:-KGYxsYRVWtnEw4HX1jj:-499146009) ([raw file](https://github.com/powershell/xscsma/blob/62324f2a71a9cf1874415eac6239f2400bc4754e/README.md#L122)):_
Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xscsma/5)_

**Pull request merged**
