### PR TITLE
MSFT_xSCSMAWebServiceServerSetup: Fixes Issue 29

### LINKED ISSUE #29: MSFT_xSCSMAWebServiceServerSetup: 'https://localhost' hardcoded in the Get/Set/Test functions, which breaks the resource when trying to set bindings
#### Details of the scenario you tried and the problem that is occurring
When attempting to harden the SMA IIS site by specifying the hostname and IP address for the site's bindings after the service is installed, the resource fails when executing `Get/New-SmaRunbookWorkerDeployment`, because the Web Service Endpoint is hardcoded in the resource as `https://localhost` (and does not specify the port either).

#### Verbose logs showing the problem
sma-webserviceerror

#### Suggested solution to the issue
I managed to solve the problem by replacing the hard-coded value with the `$CertificateName` variable value, which is `($env:COMPUTERNAME + "." + (Get-WmiObject -Class Win32_ComputerSystem).Domain)` by default, which could become problematic on a non-domain deployment.  There will need to be logic added to check for domain first, with error handling to attempt the hard-coded value (`https://localhost`) as a last resort.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
xSCSMAWebServiceServerSetup SMAWebService
{
    Ensure = 'Present'
    SourcePath = 'C:\source'
    SourceFolder = 'SystemCenter2016'
    FirstWebServiceServer = $true
    ApPool = $SMAWebServiceAccount
    SqlServer = 'SQL'
    SqlInstance = 'SMA'
    SqlDatabase = 'SMA'
    RunbookWorkerServers = 'SQL'
    InstallFolder = 'C:\Program Files\Microsoft System Center 2016\Orchestrator\Web Service'
    SpecifyCertificate = 'Yes'
    PsDscRunAsCredential = $ServerAdmin
    DependsOn = '[xSCSMAPowerShellSetup]SMAPowerShell'
}

xWebsite SMABinding
{
    Name = 'SMA'
    State = 'Started'
    BindingInfo = MSFT_xWebBindingInformation 
    {
        Protocol              = 'HTTPS'
        CertificateThumbprint = $certThumbprint
        CertificateStoreName  = 'My'
        Port                  = '9090'
        HostName              = "$ComputerName.$DomainName"
        IPAddress             = $BindingIPaddress
    }
    DependsOn = '[xSCSMAWebServiceServerSetup]SMAWebService'
}
```

#### The operating system the target node is running
```
OsName               : Microsoft Windows Server 2012 R2 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.17415.amd64fre.winblue_r4.141028-1500
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```
#### Version and build of PowerShell the target node is running
```
Name                           Value                                                                                                                              
----                           -----                                                                                                                              
PSVersion                      5.1.14409.1005                                                                                                                     
PSEdition                      Desktop                                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                            
BuildVersion                   10.0.14409.1005                                                                                                                    
CLRVersion                     4.0.30319.34014                                                                                                                    
WSManStackVersion              3.0                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                
SerializationVersion           1.1.0.1 
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

### PR DESCRIPTION
**Pull request by devopsjesus**
#### Pull Request (PR) description
- Added tests for Get/Test functions
- TODO: add tests for Set
- Added a try/catch block to test for $CertificateName WebServiceEndpoint to allow SMA web bindings to be set on the IIS Website

#### This Pull Request (PR) fixes the following issues
- Fixes #29 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xscsma/30)

### CODE REVIEW

**Review by robertdias — APPROVED** [review]

**Comment by devopsjesus** [comment]
@kwirkykat There doesn't seem to be a maintainer for this repo. Is it possible to have someone else perform the review/merge? Also, could I be added as a maintainer for this repo, as I foresee a few more changes in the near future?

**Comment by devopsjesus** [comment]
@gaelcolas Is there a way we can get this PR moving?

**Comment by gaelcolas** [comment]
Hi, I can add you as maintainer but we still need  someone to review it. 
I can do next week after PSConfEU.
Gael

**Review by jcwalker — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/xscsma/30)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @devopsjesus)

___
*[Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1, line 118 at r2](https://reviewable.io/reviews/powershell/xscsma/30#-LgiJydrEb5Ivz1xdD3L:-LgiJydrEb5Ivz1xdD3M:bkaab47) ([raw file](https://github.com/powershell/xscsma/blob/86610bd099d7bd01740e9264e812c813bd4fbfef/Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1#L118)):*
> ```
>                 # Clone the default params, because we're only testing
>                 # against $SQLInstance and $Ensure in the Get/Test functions
> ```

Should use <##> when a comments is multiple lines.
___
*[Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1, line 186 at r2](https://reviewable.io/reviews/powershell/xscsma/30#-LgiJ-uEBbxE5I_FgTyv:-LgiJ-uF4H2xsw_vHdSg:b8dmif1) ([raw file](https://github.com/powershell/xscsma/blob/86610bd099d7bd01740e9264e812c813bd4fbfef/Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1#L186)):*
> ```PowerShell
>                 }
> 
>                 #Create the exe file
> ```

Need a space after the hash to be in line with the style guidelines.
___
*[Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1, line 195 at r2](https://reviewable.io/reviews/powershell/xscsma/30#-LgiJVFb26RJeNFVm8M1:-LgiJVFb26RJeNFVm8M2:b-4ch72u) ([raw file](https://github.com/powershell/xscsma/blob/86610bd099d7bd01740e9264e812c813bd4fbfef/Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1#L195)):*
> ```
>                     # Test-TargetResource simply compares the passed in Ensure
>                     # against the return from Get, so we also test that here
> ```
Style guidelines want <##> to be used when a comment is more than one line.
___
*[Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1, line 203 at r2](https://reviewable.io/reviews/powershell/xscsma/30#-LgiJfedD5_YwXdQYlUs:-LgiJfedD5_YwXdQYlUt:bougxfi) ([raw file](https://github.com/powershell/xscsma/blob/86610bd099d7bd01740e9264e812c813bd4fbfef/Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1#L203)):*
> ```PowerShell
>                     $testParams.Remove('SetupCredential')
> 
>                     #Since Get alters the utility of the Ensure param to return state, we have to adjust the expected value here
> ```

Need a space between # and Since
___
*[Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1, line 247 at r2](https://reviewable.io/reviews/powershell/xscsma/30#-LgiKEsf0dFz679m4bBQ:-LgiKEsf0dFz679m4bBR:bqa9c83) ([raw file](https://github.com/powershell/xscsma/blob/86610bd099d7bd01740e9264e812c813bd4fbfef/Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1#L247)):*
> ```PowerShell
>         }
> 
>         Describe "$($script:dscResourceName)\Set-TargetResource" {
> ```

Is there nothing to test in Set-TargetResource?  If not I think we should remove this Describe block.

**Review by jcwalker — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/xscsma/30)* status: all files reviewed, 5 unresolved discussions (waiting on @devopsjesus)

**Review by jcwalker — APPROVED** [review]

**Review by devopsjesus — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/xscsma/30)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @jcwalker)

___
*[Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1, line 118 at r2](https://reviewable.io/reviews/powershell/xscsma/30#-LgiJydrEb5Ivz1xdD3L:-LhMMWhv682d8sQkp8Xz:b-7rl0jd) ([raw file](https://github.com/powershell/xscsma/blob/86610bd099d7bd01740e9264e812c813bd4fbfef/Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1#L118)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

> ```
>                 # Clone the default params, because we're only testing
>                 # against $SQLInstance and $Ensure in the Get/Test functions
> ```

Should use <##> when a comments is multiple lines.
</blockquote></details>

done.
___
*[Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1, line 186 at r2](https://reviewable.io/reviews/powershell/xscsma/30#-LgiJ-uEBbxE5I_FgTyv:-LhMMmqWCutqIKlS11ve:b-7rl0jd) ([raw file](https://github.com/powershell/xscsma/blob/86610bd099d7bd01740e9264e812c813bd4fbfef/Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1#L186)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

Need a space after the hash to be in line with the style guidelines.
</blockquote></details>

done.
___
*[Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1, line 195 at r2](https://reviewable.io/reviews/powershell/xscsma/30#-LgiJVFb26RJeNFVm8M1:-LhMMnqsEb7VCSWPjIFq:b-7rl0jd) ([raw file](https://github.com/powershell/xscsma/blob/86610bd099d7bd01740e9264e812c813bd4fbfef/Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1#L195)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

> ```
>                     # Test-TargetResource simply compares the passed in Ensure
>                     # against the return from Get, so we also test that here
> ```
Style guidelines want <##> to be used when a comment is more than one line.
</blockquote></details>

done.
___
*[Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1, line 203 at r2](https://reviewable.io/reviews/powershell/xscsma/30#-LgiJfedD5_YwXdQYlUs:-LhMMod_-IS-VEswV74C:b-7rl0jd) ([raw file](https://github.com/powershell/xscsma/blob/86610bd099d7bd01740e9264e812c813bd4fbfef/Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1#L203)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

Need a space between # and Since
</blockquote></details>

done.
___
*[Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1, line 247 at r2](https://reviewable.io/reviews/powershell/xscsma/30#-LgiKEsf0dFz679m4bBQ:-LhMMyoYBilN8MytChK-:brpmqc3) ([raw file](https://github.com/powershell/xscsma/blob/86610bd099d7bd01740e9264e812c813bd4fbfef/Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1#L247)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

Is there nothing to test in Set-TargetResource?  If not I think we should remove this Describe block.
</blockquote></details>

removed.

**Review by jcwalker — APPROVED** [review]

**Review by devopsjesus — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/xscsma/30)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @jcwalker)

___
*[Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1, line 247 at r2](https://reviewable.io/reviews/powershell/xscsma/30#-LgiKEsf0dFz679m4bBQ:-LhMNg7a0sEwwg8YoE-x:b-896fix) ([raw file](https://github.com/powershell/xscsma/blob/86610bd099d7bd01740e9264e812c813bd4fbfef/Tests/Unit/MSFT_xSCSMAWebServiceServerSetup.Tests.ps1#L247)):*
<details><summary><i>Previously, devopsjesus (Jason Ryberg) wrote…</i></summary><blockquote>

removed.
</blockquote></details>

Done.

**Review by jcwalker — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/powershell/xscsma/30)* status: all files reviewed, 5 unresolved discussions (waiting on @jcwalker)

**Review by jcwalker — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/powershell/xscsma/30#-:-LhMOsHN8cqzgMV9XuAp:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @jcwalker)

**Comment by devopsjesus** [comment]
@gaelcolas Got the PR reviewed! Can we try to get this change added to the next DSC kit release? :)

**Comment by mavratar** [comment]
@devopsjesus Jason, i'm going to run this through my lab and will comment once my testing is complete.

**Comment by slyckstyx** [comment]
Bump

**Review by mavratar — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/powershell/xscsma/30)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mavratar — APPROVED** [review]

**Review by mavratar — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/powershell/xscsma/30#-:-LjH5ofi1npB90xcMrAt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
